build:
  stage: build
  image: registry.gitlab.com/fzwoch/obs-gnome-screencast
  script:
    - meson --buildtype=release -Dc_link_args=-static-libgcc build
    - ninja -C build
    - mv build/gnome-mutter-screencast.so .
  artifacts:
    name: gnome-mutter-screencast
    paths:
      - gnome-mutter-screencast.so
